### ISSUE TITLE
Recognise a file type by shebang to use proper syntax highlight

### ISSUE THREAD

**Issue by andkirby** [madnight/nano#1]
Hi there,

```
Nano version 2.3.1
```

I see the subject doesn't work for nano. But is there any to have it?
I've created [stackoverflow question](https://stackoverflow.com/questions/55967571/can-nano-detect-file-type-without-extension-by-the-shebang-to-have-proper-syntax), but, perhaps, it's better to ask owners. :)

I got some discussion here
http://savannah.gnu.org/bugs/?24197
but there are no too many posts.

Perhaps, it can be done within *.nanorc files like this
https://github.com/madnight/nano/blob/master/syntax/sh.nanorc
but I have no idea how it can be done.

So, what do you think?

**Comment by madnight** [comment]
Sorry this is only a mirror, so we cannot deal with any Issues here.

**Comment by andkirby** [comment]
@madnight Yeah, that's what understood. =)

Could you please point me where I could add this issue?
