### ISSUE TITLE
Any file is unwritable when the home directory is set with a final /

### ISSUE THREAD

**Issue by oscmedgon** [madnight/nano#3]
I'm running a ubuntu machine with two users, both of them share the home directory, the problem comes because the second user home directory is set to `/home/user/` when I try to edit any file with this user an error is printed:
```
proppos@J501PS1024:/home/user$ echo $HOME
/home/user/
proppos@J501PS1024:/home/user$ nano .bashrc 
Unable to create directory /home/user//.local/share/nano/: Permission denied
It is required for saving/loading search history or cursor positions.
```
The error probably could be addressed by removing any `/` at the end of the user home directory.

**Comment by oscmedgon** [comment]
Here is the bug report if anyone is interested in following the state.
[https://savannah.gnu.org/bugs/index.php?60401](https://savannah.gnu.org/bugs/index.php?60401)

**Comment by madnight** [comment]
Please keep in mind that this repository is only a github mirror and not the official upstream.
